server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:33060/content_center
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        # 指定 nacos server 地址
        server-addr: localhost:8848
        namespace: 505aff4e-958c-4cc8-a6b0-7660b774a121
        cluster-name: Chengdu
        metadata:
          instanceType: content-center
          version: v1
          target-version: v1

  application:
    # 服务名称
    name: content-center

# 通过配置文件配置Ribbon
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# ribbon 饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients: user-center
